version: '3.3'
services:
  consumer:
    image: gagyizsofi/multiple_containers:consumer
    ports:
      - "8000:80"
    environment:
      - ASPNETCORE_URLS=http://+:80
  producer:
    image: gagyizsofi/multiple_containers:producer
    ports:
      - "8001:81"
    environment:
      - consumerURL=http://consumer:80
      - ASPNETCORE_URLS=http://+:81
    depends_on:
      - consumer
